export const categories: Category[] = [
  { id: "all", name: "All" },
  { id: "nibbles", name: "Nibbles" },
  { id: "hotdogs", name: "Hotdogs" },
  { id: "fries", name: "Fries" },
  { id: "sweet-treats", name: "Sweet Treats" },
  { id: "gourmet-burgers", name: "Gourmet Burgers" },
  { id: "something-else", name: "Something Else" },
  { id: "salads", name: "Salads" },
  { id: "cocktails", name: "Cocktails" },
  { id: "beer-and-wine", name: "Beer and Wine" },
  { id: "non-alcoholic", name: "Non-alcoholic" },
];

export const menuItems: MenuItem[] = [
  {
    id: 1,
    title: "Amazing Aloha Hawaiian Burger",
    imageUrl: "/assets/products/1-amazing-aloha-hawaiian-burger.jpg",
    category: "gourmet-burgers",
  },
  {
    id: 2,
    title: "Chili Double Cheese",
    imageUrl: "/assets/products/2-chili-double-cheese.jpg",
    category: "gourmet-burgers",
  },
  {
    id: 3,
    title: "Elvis Burger",
    imageUrl: "/assets/products/3-elvis-burger.jpg",
    category: "gourmet-burgers",
  },
  {
    id: 4,
    title: "Godfather",
    imageUrl: "/assets/products/4-godfather.jpg",
    category: "gourmet-burgers",
  },
  {
    id: 5,
    title: "Mommas Burger",
    imageUrl: "/assets/products/5-mommas-burger.jpg",
    category: "gourmet-burgers",
  },
  {
    id: 6,
    title: "Louisiana Chicken Burger",
    imageUrl: "/assets/products/6-louisiana-chicken-burger.jpg",
    category: "gourmet-burgers",
  },
  {
    id: 7,
    title: "Chicago Style Dawg",
    imageUrl: "/assets/products/7-chicago-style-dawg.jpg",
    category: "hotdogs",
  },
  {
    id: 8,
    title: "Old School Hotdog",
    imageUrl: "/assets/products/8-old-school-hotdog.jpg",
    category: "hotdogs",
  },
  {
    id: 9,
    title: "Texan Chili Dawg",
    imageUrl: "/assets/products/9-texan-chili-dawg.jpg",
    category: "hotdogs",
  },
  {
    id: 10,
    title: "Buffalo Wings",
    imageUrl: "/assets/products/10-buffalo-wings.jpg",
    category: "nibbles",
  },
  {
    id: 11,
    title: "Chicken Tenders",
    imageUrl: "/assets/products/11-chicken-tenders.jpg",
    category: "nibbles",
  },
  {
    id: 12,
    title: "Sticky BBQ Wings",
    imageUrl: "/assets/products/12-sticky-bbq-wings.jpg",
    category: "nibbles",
  },
  {
    id: 13,
    title: "Sweet Chili Wings",
    imageUrl: "/assets/products/13-sweet-chili-wings.jpg",
    category: "nibbles",
  },
  {
    id: 14,
    title: "Fries",
    imageUrl: "/assets/products/14-fries.jpg",
    category: "fries",
  },
  {
    id: 15,
    title: "Bacon Fries",
    imageUrl: "/assets/products/15-bacon-fries.jpg",
    category: "fries",
  },
  {
    id: 16,
    title: "Nacho Cheese Fries",
    imageUrl: "/assets/products/16-nacho-cheese-fries.jpg",
    category: "fries",
  },
  {
    id: 17,
    title: "Curly Fries",
    imageUrl: "/assets/products/17-curly-fries.jpg",
    category: "fries",
  },
  {
    id: 18,
    title: "Chicken Salad",
    imageUrl: "/assets/products/18-chicken-salad.jpg",
    category: "salads",
  },
  {
    id: 19,
    title: "Fried Chicken and Waffles",
    imageUrl: "/assets/products/19-fried-chicken-and-waffles.jpg",
    category: "something-else",
  },
  {
    id: 20,
    title: "Fried Chicken and Waffles with Bacon",
    imageUrl: "/assets/products/20-fried-chicken-and waffles-with-bacon.jpg",
    category: "something-else",
  },
  {
    id: 21,
    title: "Chocolate Milkshake",
    imageUrl: "/assets/products/21-chocolate-milkshake.jpg",
    category: "non-alcoholic",
  },
  {
    id: 22,
    title: "Cookies and Cream Milkshake",
    imageUrl: "/assets/products/22-cookies-and-cream-milkshake.jpg",
    category: "non-alcoholic",
  },
  {
    id: 23,
    title: "Mango Milkshake",
    imageUrl: "/assets/products/23-mango-milkshake.jpg",
    category: "non-alcoholic",
  },
  {
    id: 24,
    title: "Salted Caramel  Milkshake",
    imageUrl: "/assets/products/24-salted-caramel-milkshake.jpg",
    category: "non-alcoholic",
  },
  {
    id: 25,
    title: "Strawberry Milkshake",
    imageUrl: "/assets/products/25-strawberry-milkshake.jpg",
    category: "non-alcoholic",
  },
  {
    id: 26,
    title: "Heineken",
    imageUrl: "/assets/products/alcohol/1-heineken.jpg",
    category: "beer-and-wine",
  },
  {
    id: 27,
    title: "Estrella",
    imageUrl: "/assets/products/alcohol/2-estrella.jpg",
    category: "beer-and-wine",
  },
  {
    id: 28,
    title: "Corona Extra",
    imageUrl: "/assets/products/alcohol/3-corona.jpg",
    category: "beer-and-wine",
  },
  {
    id: 29,
    title: "Monteith's Crushed Apple Cider",
    imageUrl: "/assets/products/alcohol/4-monteith-crushed-apple-cider.jpg",
    category: "beer-and-wine",
  },
  {
    id: 30,
    title: "House Sauvignon Blanc",
    imageUrl: "/assets/products/alcohol/5-sauvignon-blanc.jpg",
    category: "beer-and-wine",
  },
  {
    id: 31,
    title: "Church Road Chardonnay",
    imageUrl: "/assets/products/alcohol/6-church-road-chardonnay.jpg",
    category: "beer-and-wine",
  },
  {
    id: 32,
    title: "The Ned Pinot Noir",
    imageUrl: "/assets/products/alcohol/7-ned-pinot-gris.jpg",
    category: "beer-and-wine",
  },
  {
    id: 33,
    title: "House Merlot",
    imageUrl: "/assets/products/alcohol/8-house-merlot.jpg",
    category: "beer-and-wine",
  },
  {
    id: 34,
    title: "Baby Doll Rosé",
    imageUrl: "/assets/products/alcohol/9-baby-doll-rose.jpg",
    category: "beer-and-wine",
  },
  {
    id: 35,
    title: "Brancott Estate Brut Cuveé",
    imageUrl: "/assets/products/alcohol/10-brancott.jpg",
    category: "beer-and-wine",
  },
  {
    id: 36,
    title: "Nachos",
    imageUrl: "/assets/products/26-nachos.jpg",
    category: "something-else",
  },
  {
    id: 37,
    title: "Blue Lagoon",
    imageUrl: "/assets/products/27-blue-lagoon.jpg",
    category: "cocktails",
  },
  {
    id: 38,
    title: "Pina Colada",
    imageUrl: "/assets/products/28-pina-colada.jpg",
    category: "cocktails",
  },
  {
    id: 39,
    title: "Haiwaiian Party",
    imageUrl: "/assets/products/29-hawaiian-party.jpg",
    category: "cocktails",
  },
  {
    id: 40,
    title: "Flat White",
    imageUrl: "/assets/products/30-flat-white.jpg",
    category: "non-alcoholic",
  },
];

export const merchItems: MerchItem[] = [
  {
    id: 1,
    name: "B.E.D. Front Shirt Design",
    imageUrl: "/assets/merch/blue-shirt.jpg",
  },
  {
    id: 2,
    name: "B.E.D. Back Shirt Design",
    imageUrl: "/assets/merch/white-back.jpg",
  },
  {
    id: 3,
    name: "Las Vegas Polo",
    imageUrl: "/assets/merch/las-vegas.jpg",
  },
  {
    id: 4,
    name: "Route 66 Cap",
    imageUrl: "/assets/merch/cap1.jpg",
  },
  {
    id: 5,
    name: "Hotdog Cap",
    imageUrl: "/assets/merch/cap2.jpg",
  },
  {
    id: 6,
    name: "Hamburger Cap",
    imageUrl: "/assets/merch/cap3.jpg",
  },
];

export const galleryItems: GalleryItem[] = [
  {
    src: "/assets/gallery/img1.jpg",
    alt: "Burger",
    span: "lg:col-span-2",
    link: "/bed-special?filter=gourmet-burgers",
  },
  {
    src: "/assets/gallery/img2.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:col-start-3",
    link: "/bed-special?filter=something-else",
  },
  {
    src: "/assets/gallery/img3.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:col-start-4",
    link: "/bed-special?filter=salads",
  },
  {
    src: "/assets/gallery/img4.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:row-start-2",
    link: "/bed-special?filter=fries",
  },
  {
    src: "/assets/gallery/img5.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:row-start-2",
    link: "/bed-special?filter=non-alcoholic",
  },
  {
    src: "/assets/gallery/img6.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:col-span-2 lg:row-start-2",
    link: "/bed-special?filter=nibbles",
  },
  {
    src: "/assets/gallery/img7.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:col-span-2 lg:row-start-3",
    link: "/bed-special?filter=hotdogs",
  },
  {
    src: "/assets/gallery/img8.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:col-start-3 lg:row-start-3",
    link: "/bed-special?filter=non-alcoholic",
  },
  {
    src: "/assets/gallery/img9.jpg",
    alt: "B.E.D. Red Logo",
    span: "lg:col-start-4 lg:row-start-3",
    link: "/bed-special?filter=sweet-treats",
  },
];
